#!/bin/bash -ex

DB_NAME=ampache
DB_USER=ampache
DB_PASS=turnkey_123

ADMIN_USER="admin"
#ADMIN_DOMAIN="example.com"
#ADMIN_MAIL="${ADMIN_USER}%40${ADMIN_DOMAIN}" # '@' encoded = '%40'
ADMIN_PASS=turnkey1

WEBROOT=/var/www/ampache

latest_release=$(gh_releases ampache/ampache \
    | grep -v 'alpha\|beta\|pre' | tail -1)
major_version=$(sed -En "s|^([0-9]+)\.[0-9]+.*|\1|p" <<<"$latest_release")
git clone --depth 1 --branch "release${major_version}" --no-single-branch \
    https://github.com/ampache/ampache "$WEBROOT"
git config --global --add safe.directory "$WEBROOT"

service mysql start

mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

cd $WEBROOT
chown -R www-data:www-data $WEBROOT
turnkey-composer install --no-dev --prefer-source
tkl-composer-squash-vendor

a2dissite 000-default
a2ensite ampache
a2enmod rewrite expires

service apache2 start

exit 1

sleep 1
CURL="curl -c /tmp/cookie -b /tmp/cookie"
#TOKEN=$($CURL http://localhost/setup 2>/dev/null | grep csrf-token | sed 's|^.*content="\([a-zA-Z0-9]*\)".*$|\1|')
$CURL localhost/setup
TOKEN=$($CURL localhost/setup/migrate 2>/dev/null | grep -m1 "<script nonce=" | sed 's|^.*<script nonce="\([a-zA-Z0-9]*\)".*$|\1|')
$CURL localhost/setup/user \
    --data-raw "_token=${TOKEN}&site_name=TurnKey+Snipe-IT+Asset+Management&locale=en&default_currency=USD&auto_increment_prefix=&zerofill_count=5&email_domain=${ADMIN_DOMAIN}&email_format=filastname&first_name=${ADMIN_FNAME}&last_name=${ADMIN_LNAME}&email=${ADMIN_MAIL}&username=${ADMIN_USER}&password=${ADMIN_PASS}&password_confirmation=${ADMIN_PASS}"

service mysql stop
service apache2 stop
