#!/bin/bash -e
# regenerate ampache secrets and mysql user password

. /etc/default/inithooks

WEBROOT=/var/www/ampache
CONF=$WEBROOT/.env

DB_USER=ampache
DB_PASS=$(mcookie)

sed -i "\|DB_PASSWORD=|s|=.*|=$DB_PASS|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user="$DB_USER" --pass="$DB_PASS"

sed -i "\|API_SECRET=|s|=.*|=$(mcookie)$(mcookie)|" $CONF
