ServerName localhost

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/ampache/public/
</VirtualHost>

<VirtualHost *:443>
        SSLEngine on
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/ampache/public/
</VirtualHost>

<Directory /var/www/ampache/public/>
        AllowOverride All        
        Require all granted
</Directory>

# See https://github.com/ampache/ampache/issues/3993#issue-2434020443
<Directory /var/www/ampache/public/play>
    SetEnv ap_trust_cgilike_cl 1
</Directory>
